version: "2"

run:
  timeout: 5m
  go: "1.22"
  tests: true
linters:
  enable-default: false
  disable-all: true
  enable:
    - govet
    - ineffassign
linters-settings:
  govet:
    check-shadowing: true
issues:
  exclude-use-default: false
